### ISSUE TITLE
Could we get a new release?

### ISSUE THREAD

**Issue by aoom256** [monero-rs/monero-rpc-rs#111]
The [version of this library on crates.io](https://crates.io/crates/monero-rpc) points to the release made last December, which uses an outdated version of `monero-rs`. 

Temporary fix is to `cargo add --git` with the git URL, but due to a separate issue (https://github.com/monero-rs/monero-rs/issues/162) in `monero-rs` (for the moment), you need to add the following to your Cargo.toml to get your project to build using this library.

```rust
[patch.crates-io] 
monero = { git = "https://github.com/monero-rs/monero-rs.git", branch = "vorot93/update-deps" }
``` 

So, is there anything blocking a new release? The build issue mentioned above is addressed on that branch, so it would be ideal to also see that merged and a new release made for that library as well. In both cases, only a minor version bump should be required.

**Comment by mvntainer** [comment]
I agree with @aoom256 , can this project be considered abandoned?

**Comment by h4sh3d** [comment]
Back in front of a keyboard again… I’ll have a look at monero and monero-rpc to make the necessary releases in the following days.

**Comment by mvntainer** [comment]
> Back in front of a keyboard again… I’ll have a look at monero and monero-rpc to make the necessary releases in the following days.

It's no hurry, you are not getting anything out of this and you have no obligation, I was just wandering if the projects are still being worked on, you (all of the contributors) did an awesome job

**Comment by h4sh3d** [comment]
Release [`0.4.0`](https://github.com/monero-rs/monero-rpc-rs/releases/tag/v0.4.0) is now out!

**Comment by silverpill** [comment]
@h4sh3d Any particular reason for bumping MSRV to 1.63.0? I quickly scanned the dependencies but can't find it. `curve25519-dalek` requires 1.60.0, default enum variants -> 1.62.0

**Comment by h4sh3d** [comment]
If this is wrong feel free to open a PR with correct value so it gets in release 0.4.1

**Comment by silverpill** [comment]
Yeah, [monero](https://github.com/monero-rs/monero-rs/commit/185801d359a5fc64efad0a529d74964ca3e2938b) and [base58-monero](https://github.com/monero-rs/base58-monero/commit/b4b78e7853d8365e4d138c2a31e12dfbc90965dd) are also on 1.63.0 now, but their deps doesn't seem to require 1.63.0. Not upgrading yet, will review everything in a couple of weeks.
