### ISSUE TITLE
Feature suggestion

### ISSUE THREAD

**Issue by Codi33** [monero-rs/monero-rpc-rs#129]
Please add make_integrated_address command support for wallet rpc

**Comment by qqqqqvb4** [comment]
https://github.com/monero-rs/monero-rpc-rs/pull/134

you can use my fork:

```
monero-rpc = { git = "https://github.com/qqqqqvb4/monero-rpc-rs" }
```

@Codi33

**Comment by Codi33** [comment]
Thanks, @qqqqqvb4! Hope your pull request gets merged.
